// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mnanVlGdw-eP2cQ-uJoyd1POk46VdL4',
    appId: '1:435728046956:web:b4fc67c12b1760824e7149',
    messagingSenderId: '435728046956',
    projectId: 'mantime-215d3',
    authDomain: 'mantime-215d3.firebaseapp.com',
    storageBucket: 'mantime-215d3.appspot.com',
    measurementId: 'G-MEVVY6114B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0oxKXQ7GOAqA8t3ewN6x92w4rZ4JQ3YM',
    appId: '1:435728046956:android:1aeb40c4f93209a14e7149',
    messagingSenderId: '435728046956',
    projectId: 'mantime-215d3',
    storageBucket: 'mantime-215d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGISoXrAJcDmPoOH8dUZ7APgWKV2LKGxs',
    appId: '1:435728046956:ios:f67e481223f021c74e7149',
    messagingSenderId: '435728046956',
    projectId: 'mantime-215d3',
    storageBucket: 'mantime-215d3.appspot.com',
    iosClientId: '435728046956-bdjav707vtias17cj921r85ol304cqkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mantime',
  );
}
